docs/planejamento/cronograma.md

Criação do cronograma
- closes #5 
Sem questões em aberto.

Criação cronograma.md

---

docs/planejamento/cronograma.md

Adicionada referência ao plano de ensino. Formatação do .md para melhor visualização do código. 
Atualização de documentação

Cronograma: referência

---

docs/atas/modelo.md

Falta apenas revisar :0
---
name: Template de Pull Request
about: Template padrão para criação de pull requests no repositório
---
Descreva as mudanças feitas neste pull request.
Se houver questões em aberto, observações ou algo que precise de mais revisão, por favor, liste-as aqui.

adição de modelo para atas

---

docs/index.md
mkdocs.yml

**Atualizações incluídas neste PR:**
- Atualização do MkDocs para a versão mais recente
- Adição da aba **Sobre** na documentação
- closes #1

feat: atualizando mkdocs

---

docs/planejamento/termosDeUso.md

---
name: Template de Pull Request
about: Template padrão para criação de pull requests no repositório
---
Descreva as mudanças feitas neste pull request.
- closes #<numero_da_issue>
Se houver questões em aberto, observações ou algo que precise de mais revisão, por favor, liste-as aqui.

fix: imagens

---

docs/planejamento/cronograma_executado.md

Criação Cronograma executado
Criação do cronograma executado
- closes #24 
Sem questões em aberto

docs/Criação cronograma_executado.md

---

README.md

✅ Alterações realizadas:
Correção de palavras com grafia incorreta
🧹 Observações:
Nenhuma informação foi removida ou modificada em termos de conteúdo técnico
Alterações focadas exclusivamente em melhorar a escrita e leitura do documento

fix: erro ortográfico

---

docs/inspecoes/inspecao1.md

Criação do documento de inspeçao

DOCS: criado documento para a primeira inspeção

---

docs/planejamento/cronograma.md

Este pull request corrige a formatação de uma tabela que estava desalinhada e reorganiza a seção de referências para melhorar a clareza e a padronização conforme os estilos adotados no projeto.

docs: correções

---

docs/elicitacao/index.md

Criação e agregação da página index de elicitação, incluindo o registro da técnica de introspecção.
- Issue #32 
Existem outras técnicas a serem registradas nesse documento.

doc: criação e agregação da pagina index de elicitação

---

priorizacao/first_thing_first.md

Criação de uma nova página na documentação abordando a técnica "First Things First".

Doc: Técnica first thing first

---

docs/atas/reuniao5.md

Adição de ata para a reuniao 5.
- Precisamos de um revisor pro documento!
- Precisamos de revisores na para aquelas atividades!

Criado documento de reunião 5

---

docs/elicitacao/tecnicas/analise_documentacao.md

Criando documento de análise de documentação
- closes #<numero_da_issue>
O documento precisa explicar o que é uma análise de documentação, considerando que já fazemos isso na introdução de elicitação?

DOCS: Análise de documentação

---

docs/elicitacao/entrevista.md
docs/elicitacao/tecnicas/introspecção.md

Atualizei a documentação para acrescentar os requisitos e corrigi algumas ortográfias.

Adicionando requisitos

---

docs/elicitacao/tecnicas/analise_documentacao.md
docs/elicitacao/tecnicas/questionario.md

Esse PR tem o propósito de adicionar os requisitos ao doc do questionário, que não tem requisitos. 
Adicionalmente, os requisitos aqui adicionados vão ser padronizados conforme a bilheteria digital, que segue um modelo de rastreabilidade bem bom. 
- Como podemos permitir a rastreabilidade de uma forma elegante? links para outros documentos ou apenas um id serve?
- Os requisitos aqui presentes vão ser considerados mais robustos caso possamos cruzá-los com outros obtidos em demais técnicas?

DOCS: requisitos do questionário

---

docs/elicitacao/priorizacao/index.md

Foi criada a página index que descreve as técnicas de priorização escolhidas.
Issue 39.
Acredito que não há nenhuma.

Criação da página de Priorização e definição de suas técnicas.

---

docs/elicitacao/entrevista.md
docs/priorizacao/three_level_scale.md

Aplicação do método Three Level Scale para priorização dos requisitos do projeto. O método foi utilizado para classificar os requisitos conforme critérios, contribuindo para uma melhor organização e planejamento do desenvolvimento.

Docs: Atualizando técnica Three Level Scale

---

docs/elicitacao/perfil_usuario.md
mkdocs.yml

Criação do artefato de Perfil de Usuário 
- closes #77 
Revisar se a definição do perfil está suficiente, por favor.

Criação do Perfil de Usuario

---

docs/elicitacao/requisitos_desejaveis.md
docs/elicitacao/tecnicas/entrevista.md
docs/elicitacao/tecnicas/introspecção.md
mkdocs.yml

Este pull request adiciona uma nova seção ao template de pull request chamada "Requisitos Desejáveis", para todos os requisitos desejaveis obtidos.

Editando requisitos desejaveis

---

docs/inspecoes/grupo+1/inspecao_2.md
mkdocs.yml

Elaboração da Inspeção do Grupo+1.
- closes #43

docs: adicionando a inspeção do grupo+1

---

docs/modelagem/cenarios.md

Correção dos cenários 10,11,12,13

docs: adicionando correção de cenario

---

docs/planejamento/cronograma_executado.md

Adição Cronograma executado
103

Adição Cronograma executado

---

docs/modelagem/cenarios.md

Adição do último cenário
- [ x] A documentação segue os padrões?
- [ x] Existe referência bibliográfica?

Adicionando o cenário restante

---

docs/apresentacoes/apresentacao3.md
mkdocs.yml

Adiciona o doc de apresentação 3.
Tá tudo certo :>?
O vídeo tá abrindo :>>>?

DOCS: Apresentação III

---

docs/inspecoes/grupo/inspecao_3.md

---
name: Template de Pull Request
about: Template padrão para criação de pull requests no repositório
---
Elaboração da inspeção 3 do nosso grupo

Add Inspeção 3

---

docs/modelagem/especificacao_suplementar.md

Fazendo ajustes na documentação relacionadas a especificação suplementar.

docs: ajustes

---

docs/elicitacao/requisitos_elicitados.md

Adicionei hyperlinks que direcionam para pagina da técnica de elicitação usada para obter aquele requisito.
Como funcionará os hyperlinks para outros artefatos?

Docs: Adicionando hyperlinks na tabela de elicitação

---

docs/modelagem/lexico.md

O Pull Request foi feito com o intuito de corrigir os lexicos feitos por João Pedro. A partir de agora eles seguirão o padrão dos Casos de Uso escolhidos pelo mesmo.
É necessário colocar os hyperlinks em todos os arquivos relacionados.

Docs: Ajuste do lexico para compor os UC10, UC11 e UC12

---

docs/inspecoes/grupo+1/inspecao_4.md
mkdocs.yml

Criação e elaboração do documento de inspeção do grupo+1
- closes #123 
-

criado o documento de inspeção do grupo+1

---

docs/elicitacao/tecnicas/analise_documentacao.md
docs/elicitacao/tecnicas/introspecção.md

Adiciona gravações do dia 05062025
Como as duas foram realizadas para fins de validação, é o que foi colocado como título da subseção.

Adicionando novas gravações à introspecção e análise de documentação.

---

docs/elicitacao/tecnicas/entrevista.md

Corrigindo iframes da documentação de entrevistas

Correção dos iframes

---

docs/entrega_final/resultados_alcancados.md
docs/prototipo/prototipo_JP.md

Resultados obtidos.
- closes #147

Resultados

---

docs/entrega_final/Execucao_do_projeto.md

---
Etapas de execução do projeto
---
Documento que resume as etapas de desenvolvimento do projeto

Documento que resume as etapas de desenvolvimento do projeto
